import * as Icons from "lucide-react";

export const iconMap: Record<string, any> = {
  // Navigation
  home: Icons.Home,
  menu: Icons.Menu,
  chevronLeft: Icons.ChevronLeft,
  chevronRight: Icons.ChevronRight,
  chevronUp: Icons.ChevronUp,
  chevronDown: Icons.ChevronDown,
  arrowLeft: Icons.ArrowLeft,
  arrowRight: Icons.ArrowRight,
  arrowUp: Icons.ArrowUp,
  arrowDown: Icons.ArrowDown,
  externalLink: Icons.ExternalLink,

  // Actions
  search: Icons.Search,
  edit: Icons.Edit,
  edit2: Icons.Edit2,
  edit3: Icons.Edit3,
  trash: Icons.Trash,
  trash2: Icons.Trash2,
  plus: Icons.Plus,
  minus: Icons.Minus,
  x: Icons.X,
  share: Icons.Share,
  share2: Icons.Share2,

  // Status
  check: Icons.Check,
  checkCircle: Icons.CheckCircle,
  checkCircle2: Icons.CheckCircle2,
  alertCircle: Icons.AlertCircle,
  alertTriangle: Icons.AlertTriangle,
  info: Icons.Info,
  bell: Icons.Bell,
  bellOff: Icons.BellOff,

  // User
  user: Icons.User,
  userPlus: Icons.UserPlus,
  userMinus: Icons.UserMinus,
  login: Icons.LogIn,
  logout: Icons.LogOut,
  settings: Icons.Settings,
  settings2: Icons.Settings2,
  lock: Icons.Lock,
  unlock: Icons.Unlock,

  // Media
  play: Icons.Play,
  pause: Icons.Pause,
  skipBack: Icons.SkipBack,
  skipForward: Icons.SkipForward,
  volume: Icons.Volume,
  volume1: Icons.Volume1,
  volume2: Icons.Volume2,
  volumeX: Icons.VolumeX,
  image: Icons.Image,
  video: Icons.Video,
  music: Icons.Music,

  // Files & Misc
  upload: Icons.Upload,
  download: Icons.Download,
  file: Icons.File,
  fileText: Icons.FileText,
  folder: Icons.Folder,
  folderPlus: Icons.FolderPlus,
  calendar: Icons.Calendar,
  clock: Icons.Clock,
  mapPin: Icons.MapPin,
  cloud: Icons.Cloud,
  mail: Icons.Mail,
  github: Icons.Github,
  twitter: Icons.Twitter,
  heart: Icons.Heart,
  star: Icons.Star,
  like: Icons.ThumbsUp,
};

export type IconName = keyof typeof iconMap;

export const categories = [
  {
    name: "Navigation",
    icons: [
      "home",
      "menu",
      "chevronLeft",
      "chevronRight",
      "chevronUp",
      "chevronDown",
      "arrowLeft",
      "arrowRight",
      "arrowUp",
      "arrowDown",
      "externalLink",
    ],
  },
  {
    name: "Actions",
    icons: [
      "search",
      "edit",
      "edit2",
      "edit3",
      "trash",
      "trash2",
      "plus",
      "minus",
      "x",
      "share",
      "share2",
    ],
  },
  {
    name: "Social",
    icons: [
      "heart",
      "star",
      "like",
      "github",
      "twitter",
    ],
  },
  {
    name: "Status",
    icons: [
      "check",
      "checkCircle",
      "checkCircle2",
      "alertCircle",
      "alertTriangle",
      "info",
      "bell",
      "bellOff",
    ],
  },
  {
    name: "User",
    icons: [
      "user",
      "userPlus",
      "userMinus",
      "login",
      "logout",
      "settings",
      "settings2",
      "lock",
      "unlock",
    ],
  },
  {
    name: "Media",
    icons: [
      "play",
      "pause",
      "skipBack",
      "skipForward",
      "volume",
      "volume1",
      "volume2",
      "volumeX",
      "image",
      "video",
      "music",
    ],
  },
  {
    name: "Files & Misc",
    icons: [
      "upload",
      "download",
      "file",
      "fileText",
      "folder",
      "folderPlus",
      "calendar",
      "clock",
      "mapPin",
      "cloud",
      "mail",
    ],
  },
];

