"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import Link from "next/link";
import { Check, ChevronDown, Download, Grid2X2, List, Pencil, Search, ShoppingCart, Star } from "lucide-react";
import { MarkBox, MarkBrush, MarkCircle, MarkSparkle, Sparkle } from "@/components/HandMarkers";
import { auraEase } from "@/lib/motion";
import { fontRegistry } from "@/lib/fonts/registry";

const fontFaceCss = fontRegistry.flatMap((font) => font.files.map((file) => `@font-face{font-family:"${font.name}";src:url("${file.url}") format("woff2");font-weight:${file.variable ? file.weightRange : file.weight};font-style:${file.style};font-display:swap}`)).join("");

export default function FontsPage() {
  const [search, setSearch] = useState("");
  const [mode, setMode] = useState<"Word" | "Paragraph">("Word");
  const [viewMode, setViewMode] = useState<"grid" | "list">("list");
  const [globalSize, setGlobalSize] = useState(190);
  const [customText, setCustomText] = useState("");
  const [likedFonts, setLikedFonts] = useState<string[]>(() => {
    if (typeof window === "undefined") return [];
    try { return JSON.parse(localStorage.getItem("aura-liked-fonts") || "[]"); } catch { return []; }
  });
  const [selectedFonts, setSelectedFonts] = useState<string[]>(() => {
    if (typeof window === "undefined") return [];
    try { return JSON.parse(localStorage.getItem("aura-selected-fonts") || "[]"); } catch { return []; }
  });
  useEffect(() => { localStorage.setItem("aura-liked-fonts", JSON.stringify(likedFonts)); }, [likedFonts]);
  useEffect(() => { localStorage.setItem("aura-selected-fonts", JSON.stringify(selectedFonts)); }, [selectedFonts]);
  const filteredFamilies = useMemo(() => fontRegistry.filter((font) => font.name.toLowerCase().includes(search.toLowerCase())), [search]);
  const handleModeChange = (next: "Word" | "Paragraph") => { setMode(next); setGlobalSize(next === "Paragraph" ? 24 : 190); };
  return <main className="relative mx-auto w-full max-w-[1280px] px-6 pt-10 pb-28 text-fg">
    <style dangerouslySetInnerHTML={{ __html: fontFaceCss }} />
    <header className="mb-20 flex flex-col items-center px-2 text-center"><p className="eyebrow mb-3">Type system</p><h1 className="display-clamp text-balance text-fg" style={{ fontSize: "clamp(2rem, 4.5vw + 0.5rem, 4.75rem)" }}>Font<span className="relative inline-block px-2.5 align-baseline"><Sparkle className="absolute -left-1 -top-1 h-4 w-4" delay="0s" /><Sparkle className="absolute -right-2 top-2 h-3 w-3" delay="0.5s" /><Sparkle className="absolute -bottom-1 left-3 h-2.5 w-2.5" delay="1s" /><Sparkle className="absolute -right-1 -bottom-2 h-3.5 w-3.5" delay="1.4s" /><span className="relative not-italic font-sans font-light" style={{ color: "var(--color-accent-primary)" }}>Family</span></span></h1><div aria-hidden className="mt-5 flex items-center gap-2.5"><span className="h-[2px] w-14 rounded-full bg-[var(--color-accent-primary)]/70" /><span className="h-1.5 w-1.5 rotate-45 bg-[var(--color-accent-primary)] shadow-[0_0_12px_var(--color-accent-primary)]" /><span className="h-[2px] w-14 rounded-full bg-[var(--color-accent-primary)]/70" /></div><p className="mt-7 max-w-[620px] text-pretty text-base leading-relaxed text-fg/70 md:text-lg"><MarkCircle>Arima</MarkCircle> holds the body and UI. <MarkBrush>Instrument Serif</MarkBrush> handles display moments — the place where the system <MarkSparkle>breathes</MarkSparkle>. <MarkBox>Geist Mono</MarkBox> carries code, shortcuts, and tabular numerics.</p></header>
    <section className="mb-8 flex flex-wrap items-center justify-between gap-6"><div className="group relative flex min-w-[240px] items-center border-b border-fg/25 pb-2 transition-colors group-focus-within:border-[var(--color-accent-primary)]"><Search className="mr-3 h-4 w-4 text-fg/65 transition-colors group-focus-within:text-[var(--color-accent-primary)]" /><input aria-label="Search fonts" placeholder="Search fonts..." value={search} onChange={(e) => setSearch(e.target.value)} className="bg-transparent text-[15px] text-fg outline-none placeholder:text-fg/70" /><div className="absolute bottom-[-1px] left-0 h-[2px] w-0 bg-[var(--color-accent-primary)] transition-all group-focus-within:w-full" /></div><div className="flex items-center gap-8">{(["Word", "Paragraph"] as const).map((item) => <button key={item} onClick={() => handleModeChange(item)} className={`relative pb-2 text-[14px] font-medium ${mode === item ? "text-fg" : "text-fg/60 hover:text-fg"}`}>{item}{mode === item && <motion.div layoutId="activeTab" className="absolute bottom-0 left-0 h-[2px] w-full bg-[var(--color-accent-primary)]" />}</button>)}</div><div className="flex items-center gap-6"><div className="flex items-center gap-3"><span className="text-[13px] text-fg/70">{globalSize}px</span><ChevronDown className="h-3.5 w-3.5 text-fg/60" /><input aria-label="Preview size" type="range" min="12" max="240" value={globalSize} onChange={(e) => setGlobalSize(Number(e.target.value))} className="h-1 w-24 accent-[var(--color-accent-primary)]" /></div><div className="flex items-center gap-2 border-l border-fg/25 pl-6"><button aria-label="List view" onClick={() => setViewMode("list")} className={viewMode === "list" ? "text-fg" : "text-fg/50"}><List className="h-4 w-4" /></button><button aria-label="Grid view" onClick={() => setViewMode("grid")} className={viewMode === "grid" ? "text-fg" : "text-fg/50"}><Grid2X2 className="h-4 w-4" /></button><Link aria-label="Open selected fonts" href={`/fonts/collection?fonts=${selectedFonts.join(",")}`} className={`relative transition-colors ${selectedFonts.length ? "text-[var(--color-accent-primary)]" : "text-fg/60 hover:text-fg"}`}><ShoppingCart className="h-4 w-4" />{selectedFonts.length > 0 && <span style={{ backgroundColor: "var(--color-accent-contrast)", color: "var(--color-bg)" }} className="absolute -right-2 -top-2 flex h-4 min-w-4 items-center justify-center rounded-full px-1 text-[10px] font-bold">{selectedFonts.length}</span>}</Link></div></div></section>
    <section className="mb-12"><div className="group relative flex items-center border-b border-fg/20 pb-4 pt-2 transition-colors group-focus-within:border-[var(--color-accent-primary)]"><Pencil className="mr-4 h-4 w-4 text-fg/60 transition-colors group-focus-within:text-[var(--color-accent-primary)]" /><input aria-label="Custom preview text" placeholder="Your Text" value={customText} onChange={(e) => setCustomText(e.target.value)} className="w-full bg-transparent text-[18px] text-fg outline-none placeholder:text-fg/65" /></div></section>
    <div className={viewMode === "grid" ? "grid grid-cols-1 gap-6 md:grid-cols-2" : "space-y-6"}><AnimatePresence mode="popLayout">{filteredFamilies.map((family) => <FontCard key={family.id} family={family} globalSize={globalSize} viewMode={viewMode} isLiked={likedFonts.includes(family.id)} isSelected={selectedFonts.includes(family.id)} onToggleLike={() => setLikedFonts((prev) => prev.includes(family.id) ? prev.filter((id) => id !== family.id) : [...prev, family.id])} onToggleSelect={() => setSelectedFonts((prev) => prev.includes(family.id) ? prev.filter((id) => id !== family.id) : [...prev, family.id])} onExpand={() => setViewMode("list")} customText={customText || (mode === "Word" ? family.name : `The ${family.name} type family brings a little more aura to every interface.`)} />)}</AnimatePresence></div>
  </main>;
}

function FontCard({ family, globalSize, customText, viewMode, isLiked, isSelected, onToggleLike, onToggleSelect, onExpand }: { family: (typeof fontRegistry)[number]; globalSize: number; customText: string; viewMode: "grid" | "list"; isLiked: boolean; isSelected: boolean; onToggleLike: () => void; onToggleSelect: () => void; onExpand: () => void }) {
  const [localSize, setLocalSize] = useState(globalSize); const [localWeight, setLocalWeight] = useState(family.weights[Math.min(1, family.weights.length - 1)] || 400); useEffect(() => setLocalSize(globalSize), [globalSize]);
  return <motion.article layout initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.98 }} onClick={viewMode === "grid" ? onExpand : undefined} className={`group aura-tile relative flex h-[420px] flex-col overflow-hidden p-8 transition-all hover:border-[var(--color-accent-primary)] ${viewMode === "grid" ? "cursor-pointer" : ""}`}>
    <div className="flex items-start justify-between"><div className="flex items-center gap-3"><label className="flex cursor-pointer items-center rounded p-1"><input type="checkbox" aria-label={`Select ${family.name}`} checked={isSelected} onChange={onToggleSelect} onClick={(e) => e.stopPropagation()} className="peer sr-only" /><span className="flex h-5 w-5 items-center justify-center rounded border border-fg/45 text-transparent transition-colors peer-focus-visible:ring-2 peer-focus-visible:ring-fg/40 peer-checked:border-fg/65 peer-checked:bg-transparent peer-checked:text-fg"><Check className="h-3.5 w-3.5" /></span></label><h2 className="text-[20px] font-medium text-fg/40 transition-colors group-hover:text-fg">{family.name}</h2><button aria-label={`Favorite ${family.name}`} onClick={(e) => { e.stopPropagation(); onToggleLike(); }} className={isLiked ? "text-[var(--color-accent-primary)]" : "text-fg/20 hover:text-fg/40"}><Star className={`h-5 w-5 ${isLiked ? "fill-current" : ""}`} /></button></div>{viewMode === "list" && <div className="flex items-center gap-8 opacity-0 transition-opacity group-hover:opacity-100"><label className="flex items-center gap-3 text-[11px] font-mono uppercase text-fg/40">Weight<input aria-label={`${family.name} weight`} type="range" min={Math.min(...family.weights)} max={Math.max(...family.weights)} step="100" value={localWeight} onChange={(e) => setLocalWeight(Number(e.target.value))} className="h-1 w-20 accent-[var(--color-accent-primary)]" /></label><label className="flex items-center gap-3 text-[11px] font-mono uppercase text-fg/40">Size<input aria-label={`${family.name} size`} type="range" min="12" max="240" value={localSize} onChange={(e) => setLocalSize(Number(e.target.value))} className="h-1 w-20 accent-[var(--color-accent-primary)]" /></label><a href={family.files[0]?.url} download onClick={(e) => e.stopPropagation()} className="aura-border flex items-center gap-2 rounded-lg bg-fg/5 px-3 py-1.5 text-sm text-fg/60 hover:text-fg"><Download className="h-3.5 w-3.5" />WOFF2</a></div>}</div>
    <div className="my-auto flex flex-1 items-center justify-center overflow-hidden"><motion.p key={customText} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3, ease: auraEase }} contentEditable suppressContentEditableWarning onClick={(e) => e.stopPropagation()} className="w-full bg-transparent text-center outline-none" style={{ fontFamily: `"${family.name}"`, fontSize: `${viewMode === "grid" ? Math.min(localSize, 80) : localSize}px`, fontWeight: localWeight, lineHeight: 1.2, color: "var(--color-accent-primary)" }}>{customText}</motion.p></div>
    <div className={`flex items-center justify-between text-sm text-fg/80 ${viewMode === "list" ? "opacity-0 group-hover:opacity-100" : "opacity-0"}`}><span>{family.category} · {family.weights.join(", ")}</span><span className="italic">Click on text to edit</span></div>
  </motion.article>;
}
