/* Auto-generated by scripts/generate-font-registry.mjs. Do not edit manually. */

export type FontFile = { file: string; url: string; weight: number; style: "normal" | "italic"; variable: boolean; weightRange?: string; label: string };
export type FontFamily = { id: string; name: string; slug: string; category: string; directory: string; cssUrl: string; license: { status: "review" | "approved"; redistributable: boolean; file: string; }; weights: number[]; styles: string[]; variable: { file: string; axes: { wght: string } } | null; files: FontFile[] };
export const fontRegistry: FontFamily[] = [
  {
    "id": "aktura",
    "name": "Aktura",
    "slug": "aktura",
    "category": "Experimental",
    "directory": "Aktura_Complete",
    "cssUrl": "/fonts/aktura.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      400
    ],
    "styles": [
      "normal"
    ],
    "variable": null,
    "files": [
      {
        "file": "public/fonts/Aktura_Complete/Aktura-Regular.woff2",
        "url": "/fonts/Aktura_Complete/Aktura-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      }
    ]
  },
  {
    "id": "arima",
    "name": "Arima",
    "slug": "arima",
    "category": "Experimental",
    "directory": "Arima",
    "cssUrl": "/fonts/arima.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      100,
      200,
      300,
      400,
      500,
      600,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": null,
    "files": [
      {
        "file": "public/fonts/Arima/Arima-Thin.woff2",
        "url": "/fonts/Arima/Arima-Thin.woff2",
        "weight": 100,
        "style": "normal",
        "variable": false,
        "label": "Thin"
      },
      {
        "file": "public/fonts/Arima/Arima-ExtraLight.woff2",
        "url": "/fonts/Arima/Arima-ExtraLight.woff2",
        "weight": 200,
        "style": "normal",
        "variable": false,
        "label": "ExtraLight"
      },
      {
        "file": "public/fonts/Arima/Arima-Light.woff2",
        "url": "/fonts/Arima/Arima-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Arima/Arima-Regular.woff2",
        "url": "/fonts/Arima/Arima-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Arima/Arima-Medium.woff2",
        "url": "/fonts/Arima/Arima-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Arima/Arima-SemiBold.woff2",
        "url": "/fonts/Arima/Arima-SemiBold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "SemiBold"
      },
      {
        "file": "public/fonts/Arima/Arima-Bold.woff2",
        "url": "/fonts/Arima/Arima-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "array",
    "name": "Array",
    "slug": "array",
    "category": "Experimental",
    "directory": "Array_Complete",
    "cssUrl": "/fonts/array.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      400,
      600,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": null,
    "files": [
      {
        "file": "public/fonts/Array_Complete/Array-BoldWide.woff2",
        "url": "/fonts/Array_Complete/Array-BoldWide.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "BoldWide"
      },
      {
        "file": "public/fonts/Array_Complete/Array-Regular.woff2",
        "url": "/fonts/Array_Complete/Array-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Array_Complete/Array-SemiboldWide.woff2",
        "url": "/fonts/Array_Complete/Array-SemiboldWide.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "SemiboldWide"
      },
      {
        "file": "public/fonts/Array_Complete/Array-Wide.woff2",
        "url": "/fonts/Array_Complete/Array-Wide.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Wide"
      },
      {
        "file": "public/fonts/Array_Complete/Array-Semibold.woff2",
        "url": "/fonts/Array_Complete/Array-Semibold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "Semibold"
      },
      {
        "file": "public/fonts/Array_Complete/Array-Bold.woff2",
        "url": "/fonts/Array_Complete/Array-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "britney",
    "name": "Britney",
    "slug": "britney",
    "category": "Handwritten",
    "directory": "Britney_Complete",
    "cssUrl": "/fonts/britney.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      300,
      400,
      700,
      900
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Britney_Complete/Britney-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Britney_Complete/Britney-Light.woff2",
        "url": "/fonts/Britney_Complete/Britney-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Britney_Complete/Britney-Regular.woff2",
        "url": "/fonts/Britney_Complete/Britney-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Britney_Complete/Britney-Variable.woff2",
        "url": "/fonts/Britney_Complete/Britney-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Britney_Complete/Britney-Bold.woff2",
        "url": "/fonts/Britney_Complete/Britney-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      },
      {
        "file": "public/fonts/Britney_Complete/Britney-Ultra.woff2",
        "url": "/fonts/Britney_Complete/Britney-Ultra.woff2",
        "weight": 900,
        "style": "normal",
        "variable": false,
        "label": "Ultra"
      }
    ]
  },
  {
    "id": "caveat",
    "name": "Caveat",
    "slug": "caveat",
    "category": "Handwritten",
    "directory": "Caveat",
    "cssUrl": "/fonts/caveat.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      400,
      500,
      600,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": null,
    "files": [
      {
        "file": "public/fonts/Caveat/Caveat-Regular.woff2",
        "url": "/fonts/Caveat/Caveat-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Caveat/Caveat-Medium.woff2",
        "url": "/fonts/Caveat/Caveat-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Caveat/Caveat-SemiBold.woff2",
        "url": "/fonts/Caveat/Caveat-SemiBold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "SemiBold"
      },
      {
        "file": "public/fonts/Caveat/Caveat-Bold.woff2",
        "url": "/fonts/Caveat/Caveat-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "dancingscript",
    "name": "Dancing Script",
    "slug": "dancingscript",
    "category": "Handwritten",
    "directory": "DancingScript_Complete",
    "cssUrl": "/fonts/dancingscript.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      400,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/DancingScript_Complete/DancingScript-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/DancingScript_Complete/DancingScript-Regular.woff2",
        "url": "/fonts/DancingScript_Complete/DancingScript-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/DancingScript_Complete/DancingScript-Variable.woff2",
        "url": "/fonts/DancingScript_Complete/DancingScript-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/DancingScript_Complete/DancingScript-Bold.woff2",
        "url": "/fonts/DancingScript_Complete/DancingScript-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "hoover",
    "name": "Hoover",
    "slug": "hoover",
    "category": "Handwritten",
    "directory": "Hoover_Complete",
    "cssUrl": "/fonts/hoover.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      100,
      300,
      400,
      500,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Hoover_Complete/Hoover-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Hoover_Complete/Hoover-Thin.woff2",
        "url": "/fonts/Hoover_Complete/Hoover-Thin.woff2",
        "weight": 100,
        "style": "normal",
        "variable": false,
        "label": "Thin"
      },
      {
        "file": "public/fonts/Hoover_Complete/Hoover-Light.woff2",
        "url": "/fonts/Hoover_Complete/Hoover-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Hoover_Complete/Hoover-Regular.woff2",
        "url": "/fonts/Hoover_Complete/Hoover-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Hoover_Complete/Hoover-Variable.woff2",
        "url": "/fonts/Hoover_Complete/Hoover-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Hoover_Complete/Hoover-Medium.woff2",
        "url": "/fonts/Hoover_Complete/Hoover-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Hoover_Complete/Hoover-Bold.woff2",
        "url": "/fonts/Hoover_Complete/Hoover-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "kalam",
    "name": "Kalam",
    "slug": "kalam",
    "category": "Handwritten",
    "directory": "Kalam_Complete",
    "cssUrl": "/fonts/kalam.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      300,
      400,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Kalam_Complete/Kalam-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Kalam_Complete/Kalam-Light.woff2",
        "url": "/fonts/Kalam_Complete/Kalam-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Kalam_Complete/Kalam-Regular.woff2",
        "url": "/fonts/Kalam_Complete/Kalam-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Kalam_Complete/Kalam-Variable.woff2",
        "url": "/fonts/Kalam_Complete/Kalam-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Kalam_Complete/Kalam-Bold.woff2",
        "url": "/fonts/Kalam_Complete/Kalam-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "kola",
    "name": "Kola",
    "slug": "kola",
    "category": "Handwritten",
    "directory": "Kola_Complete",
    "cssUrl": "/fonts/kola.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      400
    ],
    "styles": [
      "normal"
    ],
    "variable": null,
    "files": [
      {
        "file": "public/fonts/Kola_Complete/Kola-Regular.woff2",
        "url": "/fonts/Kola_Complete/Kola-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      }
    ]
  },
  {
    "id": "melodrama",
    "name": "Melodrama",
    "slug": "melodrama",
    "category": "Display",
    "directory": "Melodrama_Complete",
    "cssUrl": "/fonts/melodrama.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      300,
      400,
      500,
      600,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Melodrama_Complete/Melodrama-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Melodrama_Complete/Melodrama-Light.woff2",
        "url": "/fonts/Melodrama_Complete/Melodrama-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Melodrama_Complete/Melodrama-Regular.woff2",
        "url": "/fonts/Melodrama_Complete/Melodrama-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Melodrama_Complete/Melodrama-Variable.woff2",
        "url": "/fonts/Melodrama_Complete/Melodrama-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Melodrama_Complete/Melodrama-Medium.woff2",
        "url": "/fonts/Melodrama_Complete/Melodrama-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Melodrama_Complete/Melodrama-Semibold.woff2",
        "url": "/fonts/Melodrama_Complete/Melodrama-Semibold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "Semibold"
      },
      {
        "file": "public/fonts/Melodrama_Complete/Melodrama-Bold.woff2",
        "url": "/fonts/Melodrama_Complete/Melodrama-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "nippo",
    "name": "Nippo",
    "slug": "nippo",
    "category": "Sans Serif",
    "directory": "Nippo_Complete",
    "cssUrl": "/fonts/nippo.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      200,
      300,
      400,
      500,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Nippo_Complete/Nippo-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Nippo_Complete/Nippo-Extralight.woff2",
        "url": "/fonts/Nippo_Complete/Nippo-Extralight.woff2",
        "weight": 200,
        "style": "normal",
        "variable": false,
        "label": "Extralight"
      },
      {
        "file": "public/fonts/Nippo_Complete/Nippo-Light.woff2",
        "url": "/fonts/Nippo_Complete/Nippo-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Nippo_Complete/Nippo-Regular.woff2",
        "url": "/fonts/Nippo_Complete/Nippo-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Nippo_Complete/Nippo-Variable.woff2",
        "url": "/fonts/Nippo_Complete/Nippo-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Nippo_Complete/Nippo-Medium.woff2",
        "url": "/fonts/Nippo_Complete/Nippo-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Nippo_Complete/Nippo-Bold.woff2",
        "url": "/fonts/Nippo_Complete/Nippo-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "poppins",
    "name": "Poppins",
    "slug": "poppins",
    "category": "Sans Serif",
    "directory": "Poppins_Complete",
    "cssUrl": "/fonts/poppins.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      100,
      200,
      300,
      400,
      500,
      600,
      700,
      800,
      900
    ],
    "styles": [
      "normal",
      "italic"
    ],
    "variable": {
      "file": "/fonts/Poppins_Complete/Poppins-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Poppins_Complete/Poppins-Thin.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-Thin.woff2",
        "weight": 100,
        "style": "normal",
        "variable": false,
        "label": "Thin"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-ExtraLight.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-ExtraLight.woff2",
        "weight": 200,
        "style": "normal",
        "variable": false,
        "label": "ExtraLight"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-Light.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-Italic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-Italic.woff2",
        "weight": 400,
        "style": "italic",
        "variable": false,
        "label": "Italic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-BlackItalic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-BlackItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "BlackItalic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-BoldItalic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-BoldItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "BoldItalic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-ExtraBoldItalic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-ExtraBoldItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "ExtraBoldItalic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-ExtraLightItalic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-ExtraLightItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "ExtraLightItalic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-LightItalic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-LightItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "LightItalic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-MediumItalic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-MediumItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "MediumItalic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-Regular.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-SemiBoldItalic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-SemiBoldItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "SemiBoldItalic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-ThinItalic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-ThinItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "ThinItalic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-Variable.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-VariableItalic.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-VariableItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "VariableItalic"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-Medium.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-SemiBold.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-SemiBold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "SemiBold"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-Bold.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-ExtraBold.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-ExtraBold.woff2",
        "weight": 800,
        "style": "normal",
        "variable": false,
        "label": "ExtraBold"
      },
      {
        "file": "public/fonts/Poppins_Complete/Poppins-Black.woff2",
        "url": "/fonts/Poppins_Complete/Poppins-Black.woff2",
        "weight": 900,
        "style": "normal",
        "variable": false,
        "label": "Black"
      }
    ]
  },
  {
    "id": "pramukhrounded",
    "name": "Pramukh Rounded",
    "slug": "pramukhrounded",
    "category": "Experimental",
    "directory": "PramukhRounded_Complete",
    "cssUrl": "/fonts/pramukhrounded.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      200,
      300,
      350,
      400,
      600,
      700,
      800,
      900
    ],
    "styles": [
      "normal",
      "italic"
    ],
    "variable": {
      "file": "/fonts/PramukhRounded_Complete/PramukhRounded-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Extralight.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Extralight.woff2",
        "weight": 200,
        "style": "normal",
        "variable": false,
        "label": "Extralight"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Light.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Semilight.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Semilight.woff2",
        "weight": 350,
        "style": "normal",
        "variable": false,
        "label": "Semilight"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Italic.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Italic.woff2",
        "weight": 400,
        "style": "italic",
        "variable": false,
        "label": "Italic"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-BlackItalic.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-BlackItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "BlackItalic"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-BoldItalic.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-BoldItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "BoldItalic"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-ExtraboldItalic.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-ExtraboldItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "ExtraboldItalic"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-ExtralightItalic.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-ExtralightItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "ExtralightItalic"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-LightItalic.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-LightItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "LightItalic"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Regular.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-SemiboldItalic.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-SemiboldItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "SemiboldItalic"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-SemilightItalic.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-SemilightItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "SemilightItalic"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Variable.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-VariableItalic.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-VariableItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "VariableItalic"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Semibold.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Semibold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "Semibold"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Bold.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Extrabold.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Extrabold.woff2",
        "weight": 800,
        "style": "normal",
        "variable": false,
        "label": "Extrabold"
      },
      {
        "file": "public/fonts/PramukhRounded_Complete/PramukhRounded-Black.woff2",
        "url": "/fonts/PramukhRounded_Complete/PramukhRounded-Black.woff2",
        "weight": 900,
        "style": "normal",
        "variable": false,
        "label": "Black"
      }
    ]
  },
  {
    "id": "quicksand",
    "name": "Quicksand",
    "slug": "quicksand",
    "category": "Sans Serif",
    "directory": "Quicksand_Complete",
    "cssUrl": "/fonts/quicksand.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      300,
      400,
      500,
      600,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Quicksand_Complete/Quicksand-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Quicksand_Complete/Quicksand-Light.woff2",
        "url": "/fonts/Quicksand_Complete/Quicksand-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Quicksand_Complete/Quicksand-Regular.woff2",
        "url": "/fonts/Quicksand_Complete/Quicksand-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Quicksand_Complete/Quicksand-Variable.woff2",
        "url": "/fonts/Quicksand_Complete/Quicksand-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Quicksand_Complete/Quicksand-Medium.woff2",
        "url": "/fonts/Quicksand_Complete/Quicksand-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Quicksand_Complete/Quicksand-SemiBold.woff2",
        "url": "/fonts/Quicksand_Complete/Quicksand-SemiBold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "SemiBold"
      },
      {
        "file": "public/fonts/Quicksand_Complete/Quicksand-Bold.woff2",
        "url": "/fonts/Quicksand_Complete/Quicksand-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "rajdhani",
    "name": "Rajdhani",
    "slug": "rajdhani",
    "category": "Sans Serif",
    "directory": "Rajdhani_Complete",
    "cssUrl": "/fonts/rajdhani.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      300,
      400,
      500,
      600,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Rajdhani_Complete/Rajdhani-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Rajdhani_Complete/Rajdhani-Light.woff2",
        "url": "/fonts/Rajdhani_Complete/Rajdhani-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Rajdhani_Complete/Rajdhani-Regular.woff2",
        "url": "/fonts/Rajdhani_Complete/Rajdhani-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Rajdhani_Complete/Rajdhani-Variable.woff2",
        "url": "/fonts/Rajdhani_Complete/Rajdhani-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Rajdhani_Complete/Rajdhani-Medium.woff2",
        "url": "/fonts/Rajdhani_Complete/Rajdhani-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Rajdhani_Complete/Rajdhani-SemiBold.woff2",
        "url": "/fonts/Rajdhani_Complete/Rajdhani-SemiBold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "SemiBold"
      },
      {
        "file": "public/fonts/Rajdhani_Complete/Rajdhani-Bold.woff2",
        "url": "/fonts/Rajdhani_Complete/Rajdhani-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  },
  {
    "id": "satoshi",
    "name": "Satoshi",
    "slug": "satoshi",
    "category": "Sans Serif",
    "directory": "Satoshi_Complete",
    "cssUrl": "/fonts/satoshi.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      300,
      400,
      500,
      700,
      900
    ],
    "styles": [
      "normal",
      "italic"
    ],
    "variable": {
      "file": "/fonts/Satoshi_Complete/Satoshi-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-Light.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-Italic.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-Italic.woff2",
        "weight": 400,
        "style": "italic",
        "variable": false,
        "label": "Italic"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-BlackItalic.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-BlackItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "BlackItalic"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-BoldItalic.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-BoldItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "BoldItalic"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-LightItalic.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-LightItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "LightItalic"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-MediumItalic.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-MediumItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "MediumItalic"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-Regular.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-Variable.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-VariableItalic.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-VariableItalic.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "VariableItalic"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-Medium.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-Bold.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      },
      {
        "file": "public/fonts/Satoshi_Complete/Satoshi-Black.woff2",
        "url": "/fonts/Satoshi_Complete/Satoshi-Black.woff2",
        "weight": 900,
        "style": "normal",
        "variable": false,
        "label": "Black"
      }
    ]
  },
  {
    "id": "striper",
    "name": "Striper",
    "slug": "striper",
    "category": "Experimental",
    "directory": "Striper_Complete",
    "cssUrl": "/fonts/striper.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      400
    ],
    "styles": [
      "normal"
    ],
    "variable": null,
    "files": [
      {
        "file": "public/fonts/Striper_Complete/Striper-Regular.woff2",
        "url": "/fonts/Striper_Complete/Striper-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      }
    ]
  },
  {
    "id": "styro",
    "name": "Styro",
    "slug": "styro",
    "category": "Sans Serif",
    "directory": "Styro_Complete",
    "cssUrl": "/fonts/styro.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      200,
      300,
      400,
      500,
      600,
      700,
      800,
      900
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Styro_Complete/Styro-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Styro_Complete/Styro-Extralight.woff2",
        "url": "/fonts/Styro_Complete/Styro-Extralight.woff2",
        "weight": 200,
        "style": "normal",
        "variable": false,
        "label": "Extralight"
      },
      {
        "file": "public/fonts/Styro_Complete/Styro-Light.woff2",
        "url": "/fonts/Styro_Complete/Styro-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Styro_Complete/Styro-Regular.woff2",
        "url": "/fonts/Styro_Complete/Styro-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Styro_Complete/Styro-Variable.woff2",
        "url": "/fonts/Styro_Complete/Styro-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Styro_Complete/Styro-Medium.woff2",
        "url": "/fonts/Styro_Complete/Styro-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Styro_Complete/Styro-Semibold.woff2",
        "url": "/fonts/Styro_Complete/Styro-Semibold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "Semibold"
      },
      {
        "file": "public/fonts/Styro_Complete/Styro-Bold.woff2",
        "url": "/fonts/Styro_Complete/Styro-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      },
      {
        "file": "public/fonts/Styro_Complete/Styro-Extrabold.woff2",
        "url": "/fonts/Styro_Complete/Styro-Extrabold.woff2",
        "weight": 800,
        "style": "normal",
        "variable": false,
        "label": "Extrabold"
      },
      {
        "file": "public/fonts/Styro_Complete/Styro-Black.woff2",
        "url": "/fonts/Styro_Complete/Styro-Black.woff2",
        "weight": 900,
        "style": "normal",
        "variable": false,
        "label": "Black"
      }
    ]
  },
  {
    "id": "technor",
    "name": "Technor",
    "slug": "technor",
    "category": "Sans Serif",
    "directory": "Technor_Complete",
    "cssUrl": "/fonts/technor.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      200,
      300,
      400,
      500,
      600,
      700,
      900
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Technor_Complete/Technor-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Technor_Complete/Technor-Extralight.woff2",
        "url": "/fonts/Technor_Complete/Technor-Extralight.woff2",
        "weight": 200,
        "style": "normal",
        "variable": false,
        "label": "Extralight"
      },
      {
        "file": "public/fonts/Technor_Complete/Technor-Light.woff2",
        "url": "/fonts/Technor_Complete/Technor-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Technor_Complete/Technor-Regular.woff2",
        "url": "/fonts/Technor_Complete/Technor-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Technor_Complete/Technor-Variable.woff2",
        "url": "/fonts/Technor_Complete/Technor-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Technor_Complete/Technor-Medium.woff2",
        "url": "/fonts/Technor_Complete/Technor-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Technor_Complete/Technor-Semibold.woff2",
        "url": "/fonts/Technor_Complete/Technor-Semibold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "Semibold"
      },
      {
        "file": "public/fonts/Technor_Complete/Technor-Bold.woff2",
        "url": "/fonts/Technor_Complete/Technor-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      },
      {
        "file": "public/fonts/Technor_Complete/Technor-Black.woff2",
        "url": "/fonts/Technor_Complete/Technor-Black.woff2",
        "weight": 900,
        "style": "normal",
        "variable": false,
        "label": "Black"
      }
    ]
  },
  {
    "id": "telma",
    "name": "Telma",
    "slug": "telma",
    "category": "Handwritten",
    "directory": "Telma_Complete",
    "cssUrl": "/fonts/telma.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      300,
      400,
      500,
      700,
      900
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/Telma_Complete/Telma-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/Telma_Complete/Telma-Light.woff2",
        "url": "/fonts/Telma_Complete/Telma-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/Telma_Complete/Telma-Regular.woff2",
        "url": "/fonts/Telma_Complete/Telma-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/Telma_Complete/Telma-Variable.woff2",
        "url": "/fonts/Telma_Complete/Telma-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/Telma_Complete/Telma-Medium.woff2",
        "url": "/fonts/Telma_Complete/Telma-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/Telma_Complete/Telma-Bold.woff2",
        "url": "/fonts/Telma_Complete/Telma-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      },
      {
        "file": "public/fonts/Telma_Complete/Telma-Black.woff2",
        "url": "/fonts/Telma_Complete/Telma-Black.woff2",
        "weight": 900,
        "style": "normal",
        "variable": false,
        "label": "Black"
      }
    ]
  },
  {
    "id": "trenchslab",
    "name": "Trench Slab",
    "slug": "trenchslab",
    "category": "Display",
    "directory": "TrenchSlab_Complete",
    "cssUrl": "/fonts/trenchslab.css",
    "license": {
      "status": "review",
      "redistributable": false,
      "file": "public/fonts/LICENSE (collection license; upstream font license still required)"
    },
    "weights": [
      300,
      400,
      500,
      600,
      700
    ],
    "styles": [
      "normal"
    ],
    "variable": {
      "file": "/fonts/TrenchSlab_Complete/TrenchSlab-Variable.woff2",
      "axes": {
        "wght": "100 900"
      }
    },
    "files": [
      {
        "file": "public/fonts/TrenchSlab_Complete/TrenchSlab-Light.woff2",
        "url": "/fonts/TrenchSlab_Complete/TrenchSlab-Light.woff2",
        "weight": 300,
        "style": "normal",
        "variable": false,
        "label": "Light"
      },
      {
        "file": "public/fonts/TrenchSlab_Complete/TrenchSlab-Regular.woff2",
        "url": "/fonts/TrenchSlab_Complete/TrenchSlab-Regular.woff2",
        "weight": 400,
        "style": "normal",
        "variable": false,
        "label": "Regular"
      },
      {
        "file": "public/fonts/TrenchSlab_Complete/TrenchSlab-Variable.woff2",
        "url": "/fonts/TrenchSlab_Complete/TrenchSlab-Variable.woff2",
        "weight": 400,
        "style": "normal",
        "variable": true,
        "weightRange": "100 900",
        "label": "Variable"
      },
      {
        "file": "public/fonts/TrenchSlab_Complete/TrenchSlab-Medium.woff2",
        "url": "/fonts/TrenchSlab_Complete/TrenchSlab-Medium.woff2",
        "weight": 500,
        "style": "normal",
        "variable": false,
        "label": "Medium"
      },
      {
        "file": "public/fonts/TrenchSlab_Complete/TrenchSlab-Semibold.woff2",
        "url": "/fonts/TrenchSlab_Complete/TrenchSlab-Semibold.woff2",
        "weight": 600,
        "style": "normal",
        "variable": false,
        "label": "Semibold"
      },
      {
        "file": "public/fonts/TrenchSlab_Complete/TrenchSlab-Bold.woff2",
        "url": "/fonts/TrenchSlab_Complete/TrenchSlab-Bold.woff2",
        "weight": 700,
        "style": "normal",
        "variable": false,
        "label": "Bold"
      }
    ]
  }
] as FontFamily[];
export const fontBySlug = (slug: string) => fontRegistry.find((font) => font.slug === slug);
